### PR TITLE
 test: Add a HandlerBaseTest #46

### PR DESCRIPTION
**Pull request by NGenetzky**
issue: #46 
status: merge

The following TODOs are noted but out of scope for this PR

### TODO: handler.split() is prepending '\n' to the content

```
→ grep TODO test.py 
            # TODO: YAMLHandler.split() is prepending '\n' to the content
            # TODO: JSONHandler.split() is prepending '\n' to the content
            # TODO: TOMLHandler.split() is prepending '\n' to the content
```

### TODO: fronmatter.load() is stripping whitespace

```
content_stripped = content.strip()
self.assertEqual(post.content, content_stripped)
```

### CODE REVIEW

**Comment by NGenetzky** [comment]
@eyeseast , would you double check that my `test_external` is using your library properly? The test pasts for every handler but JSONHandler, which seems to have a bug in the code - not the test.

I added debug code to the test to print some variables and it revealed that the front matter is getting extra delimiters added.
```
-------------------------------------------------------------------------------- posttext
{
{"something": "else", "test": "tester", "author": "bob"}
}

Title
=====

title2
------

Hello.

Just need three dashes
---

And this might break.
--------------------------------------------------------------------------------
```

**Comment by eyeseast** [comment]
@NGenetzky Haven't forgotten about this but swamped with work stuff this week. Will try to dig into it when I can come up for air.

**Comment by NGenetzky** [comment]
@eyeseast , just a gentle ping.

If you are able to do a review of this code I could likely track down and fix the bug with the JSON handler. The other two TODO's deal with whitespace, and so it could just be that we have different opinions about whitespace being preserved.

**Comment by eyeseast** [comment]
Just pushed a fix to JSON output that should resolve this issue. I'll roll a new release soon, but master should be good to go at least now.

**Comment by NGenetzky** [comment]
> Just pushed a fix to JSON output that should resolve this issue.

Sounds good, I will rebase this branch when I get a chance and make sure that the test passes.

> This might be a good argument for something like #49, where one handler needs a little special casing.

I found something similar to #49 to be essential for supporting a different kind of "frontmatter" where the metadata was actually at the back of the markdown file. 

---

Any thoughts about whitespace preservation?

**Comment by eyeseast** [comment]
👍 and merged. I'll try to cut a new release today.

**Pull request merged**
